spring:
  datasource:
    url: jdbc:mysql://192.168.101.59:3306/oidc?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        web: trace

oidc:
  issuer: http://192.168.101.46:8080/
